In [2]:
import numpy as np

In [7]:
# Top of http://deeplearning.net/software/theano/tutorial/adding.html
a = np.asarray([[1., 2], [3, 4], [5, 6]])
b = 2.0
a * b

array([[  2.,   4.],
       [  6.,   8.],
       [ 10.,  12.]])

In [25]:
import theano.tensor as T
from theano import function
# x, y, and z are all "variables"
x = T.dscalar('x') # (d)ouble (scalar) 
y = T.dscalar('y')
z = x + y
f = function([x, y], z)
f(2, 3)

array(5.0)

In [30]:
# Theano has a concept of types that is separate from the Python type system
print(type(x))
print(x.type)
print(T.dscalar)
x.type is T.dscalar

<class 'theano.tensor.var.TensorVariable'>
TensorType(float64, scalar)
TensorType(float64, scalar)


True

In [22]:
from theano import pp
pp(z) # pretty print

'(x + y)'

In [31]:
# variable.eval() can be used instead of creating a function object
z.eval({x : 2, y : 3}) == function([x, y], z)(2, 3)

True

In [39]:
x = T.dmatrix('x') #(d)ouble (matrix)
y = T.dmatrix('y')
z = x + y
f = function([x, y], z)
print(f([[1, 2], [3, 4]], [[10, 20], [30, 40]]))
print(f([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 20, 30], [40, 50, 60], [70, 80, 90]]))
try:
    print(f([[1, 2], [3, 4]], [[10, 20, 30], [40, 50, 60], [70, 80, 90]]))
except Exception:
    print("Only works on compatible matrix types.")

[[ 11.  22.]
 [ 33.  44.]]
[[ 11.  22.  33.]
 [ 44.  55.  66.]
 [ 77.  88.  99.]]
Only works on compatible matrix types.


In [49]:
# exercise at the bottom of http://deeplearning.net/software/theano/tutorial/adding.html
a = T.vector()
b = T.vector()
out = a ** 2 + b ** 2 + 2 * a * b
f = function([a, b], out)
f([1, 2, 3], [10, 20, 30])

array([  121.,   484.,  1089.])

In [48]:
f = function([a, b], a ** 2 + b ** 2 + 2 * a * b)
f([1, 2, 3], [10, 20, 30])

array([  121.,   484.,  1089.])